# Waveshare 7.3" e-paper display
api_base: "http://birdnet.local:8756"
endpoint: "/api/latest_distinct"
max_species: 10
poll_seconds: 180

display:
  backend: "epaper_7in3"
  width: 800
  height: 480
  rotate: 0

ui:
  title: "Backyard Birds"
  show_scientific: false
  line_spacing_px: 4

fonts:
  regular: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
  size_px: 26
