# Waveshare 11.9" OLED Touchscreen (portrait)
api_base: "http://birdnet.local:8756"
endpoint: "/api/latest_distinct"
max_species: 12
poll_seconds: 45

display:
  backend: "waveshare_11in9"
  width: 400
  height: 1280
  rotate: 0

ui:
  title: "Backyard Birds"
  show_scientific: false
  line_spacing_px: 6

fonts:
  regular: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
  size_px: 32
