api_base: "http://birdnet.local:8756"
endpoint: "/api/latest_distinct"
max_species: 10
poll_seconds: 60

display:
  backend: "waveshare_11in9"   # "waveshare_11in9" | "epaper_7in3" | "stdout"
  width: 400
  height: 1280
  rotate: 0

ui:
  title: "Backyard Birds"
  show_scientific: false
  line_spacing_px: 6

fonts:
  regular: "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
  size_px: 30
